# Generated by Django 5.1.9 on 2025-11-21 16:04

import adl_fieldclimate_plugin.validators
import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0035_alter_dispatchchannelstationlink_dispatch_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldClimateConnection',
            fields=[
                ('networkconnection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.networkconnection')),
                ('client_id', models.CharField(max_length=255, verbose_name='Client ID')),
                ('client_secret', models.CharField(max_length=255, verbose_name='Client Secret')),
                ('username', models.CharField(max_length=255, verbose_name='Username')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
            ],
            options={
                'verbose_name': 'FieldClimate API Connection',
                'verbose_name_plural': 'FieldClimate API Connections',
            },
            bases=('core.networkconnection',),
        ),
        migrations.CreateModel(
            name='FieldClimateStationLink',
            fields=[
                ('stationlink_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.stationlink')),
                ('fc_station_code', models.CharField(max_length=100, verbose_name='FieldClimate Station Code')),
                ('start_date', models.DateTimeField(blank=True, help_text='The date to start collection data for the first collection. Ignored if any data has been collected already for this station', null=True, validators=[adl_fieldclimate_plugin.validators.validate_start_date], verbose_name='Initial Collection start date')),
            ],
            options={
                'verbose_name': 'FieldClimate Station Link',
                'verbose_name_plural': 'FieldClimate Station Links',
            },
            bases=('core.stationlink',),
        ),
        migrations.CreateModel(
            name='FieldClimateStationLinkVariableMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('fc_variable_code', models.CharField(max_length=100, verbose_name='FieldClimate Variable Code')),
                ('adl_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dataparameter', verbose_name='ADL Parameter')),
                ('fc_variable_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unit', verbose_name='FieldClimate Parameter Unit')),
                ('station_link', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_mappings', to='adl_fieldclimate_plugin.fieldclimatestationlink', verbose_name='FieldClimate Station Link')),
            ],
            options={
                'verbose_name': 'FieldClimate Station Link Variable Mapping',
                'verbose_name_plural': 'FieldClimate Station Link Variable Mappings',
            },
        ),
    ]
